### ISSUE TITLE
Testcase about A2

### ISSUE THREAD

**Issue by liuyufei** [pascal-lab/Tai-e-assignments#2]
Can you provide more tips about the testcase of A2, the acceptance of A2 is only 2%. 51 of the 52 methods were passed for my program, for the last method I have no idea about the reason.

**Comment by FXTi** [comment]
+1

**Comment by liuyufei** [comment]
Nice！

**Comment by bluesadi** [comment]
Thanks for your issue! I also got stuck in this case...

**Comment by Mosk0ng** [comment]
Thanks for your issue, 
And another(51/52),
when you init the boundary with the params of the method, remember to check if **they can hold an int value**.

**Comment by saltfishmx** [comment]
nice！thank you

**Comment by retanoj** [comment]
Deal with stmt type in `transferNode`, carefully :)
<img width="820" alt="image" src="https://user-images.githubusercontent.com/6688779/212797375-5b174570-7833-46f8-9519-5670594ccaca.png">


And, "otherwise UNDEF" condition
<img width="927" alt="image" src="https://user-images.githubusercontent.com/6688779/212797315-e9942d7b-636a-483b-a3f9-f6e0605079e2.png">

**Comment by CharesFang** [comment]
Just be careful when you are processing div 0 or rem 0 operations...
Kindly note: when op1 is `nac`, you still have to consider the situations above. 
Hope you all well!

**Comment by 1sunny** [comment]
nac / 0: this case is so hard to think of
