### ISSUE TITLE
Question about A3

### ISSUE THREAD

**Issue by SolLupus** [pascal-lab/Tai-e-assignments#24]
```Analyze 42 methods, pass 41 methods
There are 516 dead Stmts in all test cases
Your submission correctly detects 516 dead Stmts
#false negatives: 0
#false positives: 2
```
can anyone give some tips?i trap in this situation and have no idea indeed.

**Comment by clpoz** [comment]
how do you solve it?  I also meet this problem, I don't how to solve it

**Comment by SolLupus** [comment]
I don't solve yet.i close it because no response.

**Comment by clpoz** [comment]
I figure it out!
This may be a wrong setting by Assignment creator.
Conclusion First:
**You need to remove some stmt that in the Set DeadCode with side effect even which is added in the Unreachable Detection stage.**

On the experiment document，it is said that "For this issue, we have provided an API for you to check whether the RHS expression of an assignment may have side-effects . If so, you should not report it as dead code for safety, even x is not live."
We may think **if a stmt is unreachable in control flow，then it must be dead whatever it has side-effects**. 
So we only consider  handle the side-effects in LiveVariable Analysis Stage, but in fact ,you need to consider it both in
Unreachable and LiveVariable Analysis stage.
Maybe the creator is right, because our analysis is a **may** analysis, so if a stmt is unreachable and has side-effects, it should not be a deadcode.

**Comment by SolLupus** [comment]
okay, thank you for this solutions!

**Comment by Ligh0x74** [comment]
> Maybe the creator is right, because our analysis is a **may** analysis, so if a stmt is unreachable and has side-effects, it should not be a deadcode.

Hi, I passed all the test cases, but my code marked the unreachable side effect as deadcode. Is your solution really not going to mark it as deadcode?  @clpoz 

``` java
class MyTest {

    int foo() {
        int x = 0;
        if (x == 1) {
            x = new Integer(1); // side effect
        }
        return x;
    }
}
```

```
-------------------- <MyTest: int foo()> (deadcode) --------------------
[4@L5] nop;
[5@L6] temp$0 = new java.lang.Integer;
[6@L6] invokespecial temp$0.<java.lang.Integer: void <init>(int)>(%intconst0);
[7@L6] temp$1 = invokevirtual temp$0.<java.lang.Integer: int intValue()>();
[8@L6] x = temp$1;
```

**Comment by clpoz** [comment]
it's confusing, I do passed all test cases after I add the following code before return final results.
```
 for(Stmt stmt:deadCode){
           if(stmtHasSideEffect(stmt)) 
                deadCode.remove(stmt); 
        } 
        return deadCode;  
```
where stmtHasSideEffect() is a function that implement by hasNoSideEffect().
**Conclusion First:**
I test the case you provided as following,and my result keep consistency with yours.
```
int foo() {  
        int x = 0;  
        if (x == 1) {  
            x = ten(); // side effect  
        }  
        return x;  
    }  
    int ten(){  
        return 10;  
    }  
```
```
-------------------- <DeadAssignment: int foo()> (deadcode) --------------------
[4@L15] nop;
[5@L16] temp$0 = invokevirtual %this.<DeadAssignment: int ten()>();
[6@L16] x = temp$0;
```
To my ideal solution, x = ten() should not be deadcode, but my code thinks it is, 
this conclusion is wrong absolutely:

> so if a stmt is unreachable and has side-effects, it should not be a deadcode.

But why my solution could pass all test cases is weird,maybe it is some special robustness. I will figure it out at some time.
@Ligh0x74
